### ISSUE TITLE
[Waterfox G3] about Java

### ISSUE THREAD

**Issue by hurumori** [MrAlex94/Waterfox#2237]
### What happened?

#2129 
I'm sorry.
I made a new test page for the other day's problem.

http://cur.starfree.jp/test/spainter.html

I also tested variously,
Maybe G3 thought that the <param> tag below <APPLET> tags may not be read or only partially loaded.
I created a page with a <param> tag in the test and read it with Classic, and it became almost the same as G3.

especially
```
<param name = "dir_resource" Value = "res /">
<param name = "res.zip" Value = "res / res_normal.zip">
```
It seems that the part of the part is not loaded.

![210906-090101のコピー](https://user-images.githubusercontent.com/43722233/132145845-d6d95903-1bfb-41cb-a9fa-8b84e9495483.jpg)

<PARAM> page that has been deleted

http://cur.starfree.jp/test/spainter.html

![210906-091026のコピー](https://user-images.githubusercontent.com/43722233/132145956-1954cc93-d563-41ad-8723-1a1ccdfb127c.jpg)

Thank you for developing a wonderful browser!

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
java.io.FileNotFoundException: http://cur.starfree.jp/test/res/res.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at syi.awt.Awt.openStream(Unknown Source)
	at paintchat.Res.loadZip(Unknown Source)
	at c.ShiPainter.rInit(Unknown Source)
	at c.ShiPainter.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
	at paintchat_client.Me.init(Unknown Source)
	at paintchat_client.Me.confirm(Unknown Source)
	at paintchat_client.Me.alert(Unknown Source)
	at c.Ts.alert(Unknown Source)
	at c.ShiPainter.rInit(Unknown Source)
	at c.ShiPainter.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
	at paintchat.normal.Tools.makeList(Unknown Source)
	at paintchat.normal.Tools.setSize(Unknown Source)
	at syi.awt.LComponent.setDimension(Unknown Source)
	at paintchat.normal.Tools.init(Unknown Source)
	at c.P.init(Unknown Source)
	at c.ShiPainter.rInit(Unknown Source)
	at c.ShiPainter.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/issues/2129#issuecomment-998897678
