### ISSUE TITLE
Python 3.10 import error with 'Iterable collections' Arch AUR during build process.

### ISSUE THREAD

**Issue by Hi-Phile** [MrAlex94/Waterfox#2818]
### What happened?

Unable to complete build process using Python 3.10 from Arch AUR.
Found the following related discussion:
https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
==> Extracting sources...
  -> Extracting Waterfox-G3.2.4.tar.gz with bsdtar
==> Starting prepare()...
patching file toolkit/xre/nsAppRunner.cpp
Hunk #1 succeeded at 3744 (offset -88 lines).
patching file widget/gtk/nsAppShell.cpp
Hunk #2 succeeded at 176 (offset 16 lines).
patching file .cargo/config.in
patching file Cargo.lock
patching file Cargo.toml
patching file third_party/rust/packed_simd/.cargo-checksum.json
patching file third_party/rust/packed_simd/Cargo.toml
patching file third_party/rust/packed_simd/build.rs
patching file third_party/rust/packed_simd/src/api/shuffle.rs
patching file third_party/rust/packed_simd/src/codegen/llvm.rs
patching file third_party/rust/packed_simd/src/lib.rs
==> Starting build()...
Building instrumented browser...
Traceback (most recent call last):
  File "/var/cache/private/pamac/waterfox/src/Waterfox-G3.2.4/./mach", line 235, in <module>
    main(sys.argv[1:])
  File "/var/cache/private/pamac/waterfox/src/Waterfox-G3.2.4/./mach", line 227, in main
    mach = get_mach()
  File "/var/cache/private/pamac/waterfox/src/Waterfox-G3.2.4/./mach", line 209, in get_mach
    mach = check_and_get_mach(dir_path)
  File "/var/cache/private/pamac/waterfox/src/Waterfox-G3.2.4/./mach", line 165, in check_and_get_mach
    return load_mach(dir_path, mach_path)
  File "/var/cache/private/pamac/waterfox/src/Waterfox-G3.2.4/./mach", line 153, in load_mach
    return mach_bootstrap.bootstrap(dir_path)
  File "/var/cache/private/pamac/waterfox/src/Waterfox-G3.2.4/build/mach_bootstrap.py", line 203, in bootstrap
    import mach.main
  File "/var/cache/private/pamac/waterfox/src/Waterfox-G3.2.4/python/mach/mach/main.py", line 19, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
==> ERROR: A failure occurred in build().
    Aborting...
Finished with result: exit-code
Main processes terminated with: code=exited/status=4
```

**Comment by Hi-Phile** [comment]
Found out this is a deprecated build, so closing this as not an issue.  Used waterfox-classic-bin and that was able to complete build.
