### ISSUE TITLE
Cloudflare FreeCaptcha closes Waterfox

### ISSUE THREAD

**Issue by nicotine189** [MrAlex94/Waterfox#3402]
### What happened?

On accessing on a site that uses the Cloudflare captcha : the check will start and at a certain point it will stop and Waterfox will close completely (no messages no error).

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Linux

**Comment by seahorse41** [comment]
I am also seeing this, crashed 5 times in the last hour.
I now have a repeatable process, and a gdb backtrace.
running version 6.6.7 (64-bit) on debian,
Load a web page with the cloudflare test as a gate keeper.
If you wiggle the mouse around the animation, you pass.
If you immediately (before the page finishes loading) move the mouse to another window (my xfwm is configured for follow focus), make a different window Active, then your lack of input in waterfox is interpreted as a bot, and it crashes completely, all tabs, all browser windows.

`$ gdb /usr/local/bin/waterfox
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
   [clip excessive lines]
Reading symbols from /usr/local/bin/waterfox...
(No debugging symbols found in /usr/local/bin/waterfox)
(gdb) run
Starting program: /usr/local/bin/waterfox 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff74ff700 (LWP 523976)]
[Thread 0x7ffff74ff700 (LWP 523976) exited]
[Detaching after fork from child process 523977]
[New Thread 0x7ffff74ff700 (LWP 523978)]
   [clip repeating lines]
ATTENTION: default value of option mesa_glthread overridden by environment.
[New Thread 0x7fffdacfe700 (LWP 524079)]
[Detaching after fork from child process 524080]
[Thread 0x7fffdeebc700 (LWP 524022) exited]
[New Thread 0x7fffdacbd700 (LWP 524089)]
   [clip repeating lines, see process counter incremented over 600]
[New Thread 0x7fffa18ff700 (LWP 524613)]
ATTENTION: default value of option mesa_glthread overridden by environment.
[Thread 0x7fffbf896700 (LWP 524418) exited]
[New Thread 0x7fff9f9f9700 (LWP 524614)]
[New Thread 0x7fff9f1f8700 (LWP 524615)]
[New Thread 0x7fff9e9f7700 (LWP 524616)]
[New Thread 0x7fff9e1f6700 (LWP 524617)]
[New Thread 0x7fff9d9f5700 (LWP 524618)]
[New Thread 0x7fff9d1f4700 (LWP 524619)]
[New Thread 0x7fff9c9f3700 (LWP 524620)]
[New Thread 0x7fff9c1f2700 (LWP 524621)]
[New Thread 0x7fff9b9f1700 (LWP 524622)]
[New Thread 0x7fff9b1f0700 (LWP 524623)]
[New Thread 0x7fff9a9ef700 (LWP 524624)]
[New Thread 0x7fff9a1ee700 (LWP 524625)]
[New Thread 0x7fffbf896700 (LWP 524626)]
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
[New Thread 0x7fff999ed700 (LWP 524627)]
[Thread 0x7fffb1abb700 (LWP 524612) exited]

Thread 143 "CanvasRenderer" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff999ed700 (LWP 524627)]
0x00007fffa086cac0 in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
(gdb) bt
#0  0x00007fffa086cac0 in  () at /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#1  0x00007fffa0870080 in  () at /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#2  0x00007fffa0864adf in  () at /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#3  0x00007fffa0864957 in  () at /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#4  0x00007ffff7c7eea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007ffff7b9eadf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)`

**Comment by seahorse41** [comment]
Add that it also crashes in Troubleshoot mode, so not an extension.
