### ISSUE TITLE
fatal error processing mozbuild file - waterfox 6.5.0, freebsd

### ISSUE THREAD

**Issue by Martinfx** [MrAlex94/Waterfox#3589]
### What happened?

Hi,
i tried building on FreeBSD with poudriere (jail) and I have problem with **Exception: python/mozboot/**/*android* did not match anything WARNING: python/mozboot/**/*android* did not match anything**
[waterfox-6.5.0,1.log](https://github.com/user-attachments/files/17597820/waterfox-6.5.0.1.log)
clang : FreeBSD clang version 17.0.6 (https://github.com/llvm/llvm-project.git llvmorg-17.0.6-0-g6009708b4367)
uname: FreeBSD hades 13.3-RELEASE-p7 FreeBSD 13.3-RELEASE-p7 GENERIC amd64

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

waterfox-6.5.0

### What platform are you seeing the problem on?

FreeBSD

### Relevant log output

```
checking for Python 3... /wrkdirs/usr/ports/www/waterfox/work/.mozbuild/srcdirs/Waterfox-6.5.0-45c12b14f2ba/_virtualenvs/build/bin/python (3.11.10)
Error loading tasks for kind toolchain:
Traceback (most recent call last):
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/third_party/python/taskcluster_taskgraph/taskgraph/generator.py", line 311, in _run
    new_tasks = kind.load_tasks(
                ^^^^^^^^^^^^^^^^
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/third_party/python/taskcluster_taskgraph/taskgraph/generator.py", line 76, in load_tasks
    tasks = [
            ^
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/third_party/python/taskcluster_taskgraph/taskgraph/generator.py", line 76, in <listcomp>
    tasks = [
            ^
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 2290, in check_run_task_caches
    for task in tasks:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 2200, in check_task_dependencies
    for task in tasks:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 2186, in check_task_identifiers
    for task in tasks:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 2167, in chain_of_trust
    for task in tasks:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 1970, in build_task
    for task in tasks:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 1943, in set_task_and_artifact_expiry
    for job in jobs:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 1916, in try_task_config_routes
    for task in tasks:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 1903, in try_task_config_chemspill_prio
    yield from tasks
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 1883, in try_task_config_env
    yield from tasks
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 1850, in add_index_routes
    for task in tasks:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 1645, in validate
    for task in tasks:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 1623, in task_name_from_label
    for task in tasks:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 1613, in setup_raptor
    for task in tasks:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 1557, in set_defaults
    for task in tasks:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/task.py", line 1533, in set_implementation
    for task in tasks:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/cached_tasks.py", line 65, in cache_task
    for task in order_tasks(config, tasks):
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/cached_tasks.py", line 20, in order_tasks
    pending = deque(tasks)
              ^^^^^^^^^^^^
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/job/__init__.py", line 289, in use_fetches
    jobs = list(jobs)
           ^^^^^^^^^^
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/job/__init__.py", line 248, in use_system_python
    for job in jobs:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/job/__init__.py", line 229, in make_task_description
    configure_taskdesc_for_run(
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/job/__init__.py", line 514, in configure_taskdesc_for_run
    func(config, job, taskdesc)
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/job/toolchain.py", line 247, in docker_worker_toolchain
    common_toolchain(config, job, taskdesc, is_docker=True)
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/job/toolchain.py", line 170, in common_toolchain
    digest_data = get_digest_data(config, run, taskdesc)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/transforms/job/toolchain.py", line 82, in get_digest_data
    data = [hash_paths(GECKO, files)]
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.0/taskcluster/gecko_taskgraph/util/hash.py", line 57, in hash_paths
    raise Exception("%s did not match anything" % pattern)
Exception: python/mozboot/**/*android* did not match anything
WARNING: python/mozboot/**/*android* did not match anything
```

**Comment by Martinfx** [comment]
fixed in this patch https://hg.mozilla.org/releases/mozilla-esr128/rev/ac0b3057170e#l1.13
